security:
    password_hashers:
        main:
            algorithm: bcrypt
            cost: 13
        App\Entity\User: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            form_login:
                login_path: connexion
                check_path: connexion
            
            remember_me:
                secret:   '%kernel.secret%' # requis
                lifetime: 604800 # 1 semaine en secondes

            logout:
                path: app_logout

                
    # access_control:
    #     - { path: ^/admin, roles: admin }

when@dev:
    security:
        password_hashers:
            main:
                algorithm: bcrypt
                cost: 4 